### ISSUE TITLE
Assistant support requested for new fields for search skills results

### ISSUE THREAD

**Issue by patnogay** [watson-developer-cloud/salesforce-sdk#187]
We want to demo the new Discovery search skill in WatsonAssistant from Salesforce.
To do this we need the new fields returned in IBMAssistantV2Models for output/generic/header and output/generic/results.
  I have coded the additions to IBMAssistantV2Models.apxc for handling the deserialization of the new return fields and tested them in my local SF org.  Let me know if you want the updated source.

**Comment by lpatino10** [comment]
Hey @patnogay. There was some discussion over Slack, but your request is for a beta feature which we don't support in the SDKs. I'm going to go ahead and close this issue since we generate the SDKs programmatically and the feature you're asking for should be added once it's publicly available.

Sorry for the inconvenience!
