### ISSUE TITLE
Code coverage for Apex classes less than 75%

### ISSUE THREAD

**Issue by posolutionez** [watson-developer-cloud/salesforce-sdk#197]
When trying to use the SDK for Assistant and/or NaturalLanguageUnderstanding capabilities, we're having issues installing the SDK files in our production org due to the fact that many of the tests do not have 75% code coverage or better. Since this is enforced by SF for production organizations, should this be considered a bug with this SDK? I am using the latest version of the SDK files here. Please advise and thanks!

**Comment by lpatino10** [comment]
@posolutionez the fix is on its way out now, and should be in `v4.4.2` as I mentioned before. The code coverage I'm getting post-fix are:

- 81% with the full SDK deployed
- 79% with Assistant v1, Assistant v2, Natural Language Understanding, and the core classes deployed

Please let me know if for whatever reason this doesn't solve the problem.

**Comment by daiyaharsh90** [comment]
Hello lpation10,

I work with posolutionez (Patrick) and we deployed the fix to our sandbox but there are still some classes which fall below the 75% threshold.

Following are the classes-
IBMWatsonDynamicResponseModel - 0%
IBMWatsonIAMToken - 60%
IBMWatsonICP4DToken - 73%
IBMWatsonICP4DTokenResponse - 5%
IBMWatsonNoauthAuthenticator - 25%
IBMWatsonResponseModel - 46%
IBMWatsonService - 73%

We are leveraging Watson Assistant and NLU part of the SDK but due to dependency between the classes above mentioned classes are also needed. When we deploy code from Sandbox to Stage and Production all classes need to have a minimum of 75% coverage it doesn't look for the whole SDK coverage. Please advice.
