### ISSUE TITLE
deploy to salesforce doesn't work

### ISSUE THREAD

**Issue by stevemart** [watson-developer-cloud/salesforce-sdk#73]
Trying to use the deploy to SFDX button results in an error. Sorry for the lack of detail here but there isn't much to go on...

#### Salesforce version

* Not sure?

#### SDK version

* from master branch

#### Steps to reproduce

* Create a salesforce account, which i access through https://na50.lightning.force.com/
* Click the `Deploy to SFDX` button
* Authorize the application

<img width="735" alt="allow_perms" src="https://user-images.githubusercontent.com/4118756/36131862-0a9e21ae-1042-11e8-80c2-69f8f679d4e1.png">

* Error is generated

<img width="606" alt="error" src="https://user-images.githubusercontent.com/4118756/36131872-198134f4-1042-11e8-8cc3-fb28777d1ad9.png">

**Comment by lpatino10** [comment]
Hey Steve, thanks for bringing this issue up. I think I may have found the source of the issue here.

First, can you confirm that the Salesforce org you're trying to deploy to is a Dev Hub org? That's the only type of org the button works with and I admittedly haven't made it very clear in the README.

The more likely cause is that it seems the Deploy to SFDX button has an issue with deploying if the target URL isn't the root URL of the project. This issue in their repo [here](https://github.com/wadewegner/deploy-to-sfdx/issues/37) seems to confirm that. If you were trying to deploy from `master`, the URL should've been `https://github.com/watson-developer-cloud/salesforce-sdk/tree/master`.

I'm going to make `master` the base branch, so you shouldn't have an issue after that change, but next time you try just make sure the URL is `https://github.com/watson-developer-cloud/salesforce-sdk`.

Let me know if you still have any problems after trying again.

**Comment by stevemart** [comment]
Hey @lpatino10 thanks for taking a look at this and your quick analysis.

> First, can you confirm that the Salesforce org you're trying to deploy to is a Dev Hub org? That's the only type of org the button works with and I admittedly haven't made it very clear in the README.

I really couldn't tell you with any certainty if i'm doing this correctly. No prompt came up to select an org to deploy to. From what I've been reading online, I know how to bring up the dev console, but I can't seem to run anything. Google tells me this is a permissions issue and I don't have an `Author Apex` role, but I don't know how to add this even after looking in the console for an hour :)

**Comment by lpatino10** [comment]
When you click on the deployment button, do you get this page?

![screen shot 2018-02-13 at 11 41 05 am](https://user-images.githubusercontent.com/8710772/36161887-d942ed8a-10b2-11e8-9c60-bb875b137da5.png)

That link under the `Login with your Dev Hub org` button will take you to the page to create a Dev Hub org if you're not sure you have one.

If it's something Salesforce-specific with permissions I'm not sure of the best way to help 😕

**Comment by stevemart** [comment]
@lpatino10 The link in the text "Need a Dev Hub org? Learn how to get one here" links out to https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm 

I'm *assuming* my account is fine since it's a trial account and the third item on that page says:

>  If you're using a trial org, Dev Hub is already enabled.

**Comment by stevemart** [comment]
I got slightly further by pausing AdBlock...

```
We can't authorize you because of an OAuth error. For more information, contact your Salesforce administrator.

OAUTH_APPROVAL_ERROR_GENERIC : An unexpected error has occured during authentication. Please try again.
```

<img width="410" alt="screen shot 2018-02-13 at 9 13 54 pm" src="https://user-images.githubusercontent.com/4118756/36184627-e725e6f0-1102-11e8-8e37-dae77cf22851.png">

**Comment by stevemart** [comment]
@lpatino10 you can ignore this issue for now. I'm spinning my wheels trying to get salesforce to actually do something that isn't tossing up an error. I'm a while away from being able to use the SDK.

**Comment by lpatino10** [comment]
Will do. Good luck figuring it out!
